# -*- coding: utf-8 -*-
"""test_petstore_api

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ktdYuZ4DAv-vI5_c_25eDpAn7PvL0FbW

Установка библиотек requests и pytest.
"""

!pip install requests pytest

"""Импорт библиотек."""

import requests
import pytest

"""Создание тестовых данных для заказов с разными статусами."""

BASE_URL = "https://petstore.swagger.io/v2"

# Тестовые данные
test_order = {
    "id": 999,
    "petId": 122,
    "quantity": 1,
    "status": "placed"
}

"""Тест №1. Размещение заказа (POST)."""

def test_create_order():
    """Простое создание заказа"""
    response = requests.post(f"{BASE_URL}/store/order", json=test_order)
    assert response.status_code == 200
    print("☑ Заказ создан")

"""Тест №2. Получение заказа (GET)."""

def test_get_order():
    """Простое получение заказа"""
    response = requests.get(f"{BASE_URL}/store/order/999")
    assert response.status_code == 200
    print("☑ Заказ получен")

"""Тест №3. Удаление заказа (DELETE)."""

def test_delete_order():
    """Простое удаление заказа"""
    response = requests.delete(f"{BASE_URL}/store/order/999")
    assert response.status_code == 200
    print("☑ Заказ удалён")

"""Тест №4. Проверка отсутствия заказа."""

def test_order_not_found():
    """Проверка отсутствия заказа"""
    response = requests.get(f"{BASE_URL}/store/order/000")
    assert response.status_code == 404
    print("☑ Отсутствие заказа подтверждено")

"""Запуск тестов и вывод результатов."""

print("\n=== Начало тестирования ===")
test_create_order()
test_get_order()
test_delete_order()
test_order_not_found()
print("=== Тестирование завершено ===")